name: dum
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  audio_service: ^0.18.12
  audio_video_progress_bar: ^2.0.2
  dynamic_color: ^1.7.0
  flutter:
    sdk: flutter
  get: ^4.6.6
  just_audio: ^0.9.36
  on_audio_query: ^2.9.0
  permission_handler: ^11.3.0
  provider: ^6.1.2
  scroll_to_index: ^3.0.1
  transparent_image: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
